# Generated by Django 4.1.2 on 2022-11-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Factories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mumbai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Bl1', models.IntegerField(default=0)),
                ('Bl2', models.IntegerField(default=0)),
                ('Bl3', models.IntegerField(default=0)),
                ('Bl4', models.IntegerField(default=0)),
            ],
        ),
    ]
