# Generated by Django 4.1.2 on 2022-11-21 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Factories', '0002_mumbai'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mumbai',
            old_name='Bl1',
            new_name='Ml1',
        ),
        migrations.RenameField(
            model_name='mumbai',
            old_name='Bl2',
            new_name='Ml2',
        ),
        migrations.RenameField(
            model_name='mumbai',
            old_name='Bl3',
            new_name='Ml3',
        ),
        migrations.RenameField(
            model_name='mumbai',
            old_name='Bl4',
            new_name='Ml4',
        ),
    ]
