# Generated by Django 4.1.2 on 2022-11-21 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Factories', '0004_chennai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chennai',
            name='Ml4',
        ),
    ]
