# Generated by Django 4.1.2 on 2022-11-21 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Factories', '0005_remove_chennai_ml4'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chennai',
            old_name='Ml1',
            new_name='Cl1',
        ),
        migrations.RenameField(
            model_name='chennai',
            old_name='Ml2',
            new_name='Cl2',
        ),
        migrations.RenameField(
            model_name='chennai',
            old_name='Ml3',
            new_name='Cl3',
        ),
    ]
